"""Safe composition seams between governed decisions and paper execution."""

from .committee import CommitteeApproval, TradeCommitteeGate
from .desk import (
    AnalystBrief,
    AuthenticatedCommitteeDecision,
    CoachReflection,
    DispatchAuthorization,
    DispatchAuthorizationRejected,
    DeskCycleRequest,
    DeskCycleResult,
    DeskCycleFailed,
    DeskCycleStatus,
    DeskRuntime,
    EventBrief,
    HistoricalDecision,
    HistoricalRequest,
    MarketMood,
    PaperExecutionRequest,
    PaperTrader,
    StrategyEvidenceStats,
    desk_cycle_request_id,
)
from .intents import (
    ExecutableQuote,
    IntentBuildError,
    IntentBuildResult,
    TradeIntentFactory,
)
from .paper import GovernedPaperCoordinator, PaperAcceptance, PaperAdmissionRejected
from .roles import (
    AnalystJudgment,
    ApprovalChainCommittee,
    CommitteeInputs,
    CommitteeReviewContext,
    EarningsReporter,
    GovernedAnalyst,
    OperationalSecretary,
    OutcomeCoach,
    RegimeCrowdReader,
    StrategyHistorian,
)
from .verdicts import CommitteeVerdictAuthority, CommitteeVerdictEvidence

__all__ = [
    "CommitteeApproval",
    "CommitteeVerdictAuthority",
    "CommitteeVerdictEvidence",
    "AnalystBrief",
    "AuthenticatedCommitteeDecision",
    "CoachReflection",
    "DispatchAuthorization",
    "DispatchAuthorizationRejected",
    "DeskCycleRequest",
    "DeskCycleResult",
    "DeskCycleFailed",
    "DeskCycleStatus",
    "DeskRuntime",
    "EventBrief",
    "HistoricalDecision",
    "HistoricalRequest",
    "MarketMood",
    "PaperExecutionRequest",
    "PaperTrader",
    "StrategyEvidenceStats",
    "desk_cycle_request_id",
    "AnalystJudgment",
    "ApprovalChainCommittee",
    "CommitteeInputs",
    "CommitteeReviewContext",
    "EarningsReporter",
    "GovernedAnalyst",
    "OperationalSecretary",
    "OutcomeCoach",
    "RegimeCrowdReader",
    "StrategyHistorian",
    "ExecutableQuote",
    "IntentBuildError",
    "IntentBuildResult",
    "TradeIntentFactory",
    "GovernedPaperCoordinator",
    "PaperAcceptance",
    "PaperAdmissionRejected",
    "TradeCommitteeGate",
]
